/*
Author: bluepotato
*/
#include "CvGameCoreDLL.h"
#include "CyRFCPlayer.h"
#include "CyRFCUnit.h"
#include "CyRFCCity.h"

void CyRFCPlayerInterface() {
	python::class_<CyRFCPlayer>("CyRFCPlayer")
		.def("setStartingYear", &CyRFCPlayer::setStartingYear, "void (int newStartingYear)")
		.def("getStartingYear", &CyRFCPlayer::getStartingYear, "int ()")
		.def("setStartingCivic", &CyRFCPlayer::setStartingCivic, "void (int category, int civic)")
		.def("setStartingGold", &CyRFCPlayer::setStartingGold, "void (int gold)")
		.def("setStartingTech", &CyRFCPlayer::setStartingTech, "void (int tech, bool value)")
		.def("setStartingPlot", &CyRFCPlayer::setStartingPlot, "void (int x, int y)")
		.def("addCoreProvince", &CyRFCPlayer::addCoreProvince, "void (int coreProvince)")
		.def("getStability", &CyRFCPlayer::getStability, "int (int category)")
		.def("getTotalStability", &CyRFCPlayer::getTotalStability, "int ()")
		.def("setEnabled", &CyRFCPlayer::setEnabled, "void (bool enabled)")
		.def("isEnabled", &CyRFCPlayer::isEnabled, "bool ()")
		.def("getStartingCivic", &CyRFCPlayer::getStartingCivic, "int (int civicOptionType)")
		.def("getStartingGold", &CyRFCPlayer::getStartingGold, "int ()")
		.def("isStartingTech", &CyRFCPlayer::isStartingTech, "bool (int startingTech)")
		.def("getStartingPlotX", &CyRFCPlayer::getStartingPlotX, "int ()")
		.def("getStartingPlotY", &CyRFCPlayer::getStartingPlotY, "int ()")
		.def("getNumScheduledUnits", &CyRFCPlayer::getNumScheduledUnits, "int ()")
		.def("getNumScheduledCities", &CyRFCPlayer::getNumScheduledCities, "int ()")
		.def("addScheduledUnit", &CyRFCPlayer::addScheduledUnit, python::return_value_policy<python::reference_existing_object>(), "()")
		.def("getScheduledUnit", &CyRFCPlayer::getScheduledUnit, python::return_value_policy<python::reference_existing_object>(), "(int i)")
		.def("addScheduledCity", &CyRFCPlayer::addScheduledCity, python::return_value_policy<python::reference_existing_object>(), "()")
		.def("getScheduledCity", &CyRFCPlayer::getScheduledCity, python::return_value_policy<python::reference_existing_object>(), "(int i)")
		.def("getNumCoreProvinces", &CyRFCPlayer::getNumCoreProvinces, "int ()")
		.def("getCoreProvince", &CyRFCPlayer::getCoreProvince, "int (int i)")
		.def("setStartingWar", &CyRFCPlayer::setStartingWar, "void (int i, bool startingWar)")
		.def("isStartingWar", &CyRFCPlayer::isStartingWar, "bool (int i)")
		.def("addRelatedLanguage", &CyRFCPlayer::addRelatedLanguage, "void (int i)")
		.def("isRelatedLanguage", &CyRFCPlayer::isRelatedLanguage, "bool (int i)")
		.def("isMinor", &CyRFCPlayer::isMinor, "bool ()")
		.def("isSpawned", &CyRFCPlayer::isSpawned, "bool ()")
		.def("setMinorCiv", &CyRFCPlayer::setMinorCiv, "void (bool minor)")
		.def("isFlipped", &CyRFCPlayer::isFlipped, "bool ()")
		.def("setFlipped", &CyRFCPlayer::setFlipped, "void (bool flipped)")
		.def("setCompactEmpireModifier", &CyRFCPlayer::setCompactEmpireModifier, "void (int modifier)")
		.def("getCompactEmpireModifier", &CyRFCPlayer::getCompactEmpireModifier, "int ()")
		.def("setUnitUpkeepModifier", &CyRFCPlayer::setUnitUpkeepModifier, "void (int modifier)")
		.def("getUnitUpkeepModifier", &CyRFCPlayer::getUnitUpkeepModifier, "int ()")
		.def("setResearchModifier", &CyRFCPlayer::setResearchModifier, "void (int modifier)")
		.def("getResearchModifier", &CyRFCPlayer::getResearchModifier, "int ()")
		.def("setDistanceMaintenanceModifier", &CyRFCPlayer::setDistanceMaintenanceModifier, "void (int modifier)")
		.def("getDistanceMaintenanceModifier", &CyRFCPlayer::getDistanceMaintenanceModifier, "int ()")
		.def("setNumCitiesMaintenanceModifier", &CyRFCPlayer::setNumCitiesMaintenanceModifier, "void (int modifier)")
		.def("getNumCitiesMaintenanceModifier", &CyRFCPlayer::getNumCitiesMaintenanceModifier, "int ()")
		.def("setUnitProductionModifier", &CyRFCPlayer::setUnitProductionModifier, "void (int modifier)")
		.def("getUnitProductionModifier", &CyRFCPlayer::getUnitProductionModifier, "int ()")
		.def("setCivicUpkeepModifier", &CyRFCPlayer::setCivicUpkeepModifier, "void (int modifier)")
		.def("getCivicUpkeepModifier", &CyRFCPlayer::getCivicUpkeepModifier, "int ()")
		.def("setHealthBonusModifier", &CyRFCPlayer::setHealthBonusModifier, "void (int modifier)")
		.def("getHealthBonusModifier", &CyRFCPlayer::getHealthBonusModifier, "int ()")
		.def("setBuildingProductionModifier", &CyRFCPlayer::setBuildingProductionModifier, "void (int modifier)")
		.def("getBuildingProductionModifier", &CyRFCPlayer::getBuildingProductionModifier, "int ()")
		.def("setWonderProductionModifier", &CyRFCPlayer::setWonderProductionModifier, "void (int modifier)")
		.def("getWonderProductionModifier", &CyRFCPlayer::getWonderProductionModifier, "int ()")
		.def("setGreatPeopleModifier", &CyRFCPlayer::setGreatPeopleModifier, "void (int modifier)")
		.def("getGreatPeopleModifier", &CyRFCPlayer::getGreatPeopleModifier, "int ()")
		.def("setInflationModifier", &CyRFCPlayer::setInflationModifier, "void (int modifier)")
		.def("getInflationModifier", &CyRFCPlayer::getInflationModifier, "int ()")
		.def("setGrowthModifier", &CyRFCPlayer::setGrowthModifier, "void (int modifier)")
		.def("getGrowthModifier", &CyRFCPlayer::getGrowthModifier, "int ()")
		.def("setStartingReligion", &CyRFCPlayer::setStartingReligion, "void (int religion)")
		.def("getStartingReligion", &CyRFCPlayer::getStartingReligion, "int ()")
		.def("getPlayerType", &CyRFCPlayer::getPlayerType, "int ()")
		.def("removeScheduledUnit", &CyRFCPlayer::removeScheduledUnit, "void (int i)")
		.def("removeScheduledCity", &CyRFCPlayer::removeScheduledCity, "void (int i )")
		.def("removeCoreProvince", &CyRFCPlayer::removeCoreProvince, "void (int i)")
		;
}
