## Sid Meier's Civilization 4
## Copyright Firaxis Games 2005

# Enum for screens...

from CvPythonExtensions import CivilopediaPageTypes

DOMESTIC_ADVISOR = 0
REWARD_SCREEN = 1
DAWN_OF_MAN = 2
TECH_CHOOSER = 3
FOREIGN_ADVISOR = 4
FINANCE_ADVISOR = 5
WONDER_MOVIE_SCREEN = 6
RELIGION_SCREEN = 7
INTRO_MOVIE_SCREEN = 8
CIVICS_SCREEN = 9
DIPLOMACY_SCREEN = 10
OPTIONS_SCREEN = 11
TECH_SPLASH = 12
REPLAY_SCREEN = 13
MILITARY_ADVISOR = 14
VICTORY_SCREEN = 15
TOP_CIVS = 16
TUTORIAL_SCREEN = 17
INFO_SCREEN = 18
ERA_MOVIE_SCREEN = 19
ADVISOR_SCREEN = 20
HALL_OF_FAME = 21
DAN_QUAYLE_SCREEN = 22
WORLDBUILDER_SCREEN = 23
WORLDBUILDER_DIPLOMACY_SCREEN = 24
VICTORY_MOVIE_SCREEN = 25
UN_SCREEN = 26
ESPIONAGE_ADVISOR = 27
SPACE_SHIP_SCREEN = 28
CORPORATION_SCREEN = 29

## World Builder ##
WB_TRADE = 63
WB_INFO = 64
WB_CORPORATION = 65
WB_RELIGION = 66
WB_UNITLIST = 67
WB_PLOT = 68
WB_EVENT = 69
WB_BUILDING = 70
WB_CITYDATA = 71
WB_CITYEDIT = 72
WB_TECH = 73
WB_PROJECT = 74
WB_TEAM = 75
WB_PLAYER = 76
WB_UNIT = 77
WB_PROMOTION = 78
WB_DIPLOMACY = 79
WB_GAMEDATA = 80
#bluepotato
WB_RFC_PLAYER = 81
WB_RFC_PROVINCE = 82

### GameFont Display
GAMEFONT_DISPLAY_SCREEN = 92
### GameFont Display

MAIN_INTERFACE = 99
DEBUG_INFO_SCREEN = 100

# Civilopedia Pages start at 200
#################################################
## Sevopedia 2.3 BEGIN
#################################################

PEDIA_MAIN		= 200
PEDIA_TECHS		= 201
PEDIA_UNITS		= 202
PEDIA_UNIT_UPGRADES	= 203
PEDIA_UNIT_CATEGORIES	= 204
PEDIA_PROMOTIONS	= 205
PEDIA_PROMOTION_TREE	= 206
PEDIA_BUILDINGS		= 207
PEDIA_NATIONAL_WONDERS	= 208
PEDIA_GREAT_WONDERS	= 209
PEDIA_PROJECTS		= 210
PEDIA_SPECIALISTS	= 211
PEDIA_TERRAINS		= 212
PEDIA_FEATURES		= 213
PEDIA_BONUSES		= 214
PEDIA_IMPROVEMENTS	= 215
PEDIA_CIVS		= 216
PEDIA_LEADERS		= 217
PEDIA_CIVICS		= 218
PEDIA_RELIGIONS		= 219
PEDIA_CORPORATIONS	= 220
PEDIA_CONCEPTS		= 221
PEDIA_BTS_CONCEPTS	= 222
PEDIA_HINTS		= 223

#################################################
## Sevopedia 2.3 END
#################################################
#bluepotato start: mercenaries
MERCENARIES_SCREEN = 3500
#bluepotato end
